### PR TITLE
Upgrade to 1.10.9

### PR DESCRIPTION
**Pull request by jrletosa**
* Bring latest updates from https://github.com/puckel/docker-airflow
* Remove werkzeug dependency

### CODE REVIEW

**Comment by jrletosa** [comment]
why are httplib2, kubernetes and SQLAlchemy dependencies needed, @AntonErholt ? They are not in the original repository

**Comment by AntonErholt** [comment]
They required pinning since the later versions break the build. There are issues about them in the puckel repo

**Comment by jrletosa** [comment]
> They required pinning since the later versions break the build. There are issues about them in the puckel repo

But those dependencies don't appear in the puckel repo.

**Comment by AntonErholt** [comment]
https://github.com/puckel/docker-airflow/issues/499

**Comment by AntonErholt** [comment]
for 1.10.6 they were required

**Comment by AntonErholt** [comment]
not for later versions :D

**Comment by jrletosa** [comment]
stil don't see the relation between Werkzeug and httplib2, kubernetes and SQLAlchemy...

**Pull request merged**
